### PR TITLE
Update header.js

### PR DESCRIPTION
**Pull request by pratikkabade**

### CODE REVIEW

**Review by Susmita-Dey — APPROVED** [review]
Thank You

**Comment by Susmita-Dey** [comment]
@pratikkabade Can you kindly resolve the merge conflicts ASAP?

**Comment by pratikkabade** [comment]
I can't do it right now.
You can just directly **copy-paste** content from `header.js` file that could be more _easier_.

**Comment by Susmita-Dey** [comment]
> I can't do it right now. You can just directly **copy-paste** content from `header.js` file that could be more _easier_.
> 
> Or you can **squash and merge**, it'd do it

Okay, thanks

**Pull request merged**
